### PR TITLE
Improve installation procedure

### PR DESCRIPTION
**Pull request by wardsimon**
# Pip installation

In this pull request we deal with installation. It is now possible to:

## For users

```console
pip install --extra-index-url https://easyscience.github.io/pypi/ .
easyDiffraction
```

## For developers

```console
pip install --extra-index-url https://easyscience.github.io/pypi/ -e '.[ci]'
```

## Notes

In the installation an additional `--extra-index-url https://easyscience.github.io/pypi/` is added due to CFML not being released

# Snapcraft images

A snap image is also made by default and can be used on Linux based systems. When this work hits the `master` branch, the application can be found on the snap store. In the meantime the build artifact can be installed with:

```console
snap install --devmode easydiffraction*.snap
```

### CODE REVIEW

**Comment by rozyczko** [comment]
Clean Ubuntu 22.04

**pip install .** gives me 
```
ERROR: No matching distribution found for CFML<0.0.2,>=0.01
```

**snap install --dev-mode easydiffraction&ast;.snap** gives me
```
error: unknown flag `dev-mode`
```

**pip install -e '.[dev]'** gives me
```
ERROR: File "setup.py" or "setup.cfg" not found.
(A "pyproject.toml" file was found, but editable mode currently requires a setuptools-based build.)
```

**Comment by wardsimon** [comment]
Yeah, this is still the problem with no CFML release, you meed the `--extra-index-url https://easyscience.github.io/pypi/`. I've updated the main text

**Comment by rozyczko** [comment]
This works properly on Ubuntu 22.04 for the first two modes. Installing from `snap` will of course be tested only after the merge.

**Review by rozyczko — APPROVED** [review]
pip installs work good. Snap based install will be tested after merge

**Comment by wardsimon** [comment]
This should now be OK to merge

**Pull request merged**
